### ISSUE TITLE
Spike: hot reloading

### ISSUE THREAD

**Issue by LucaColonnello** [cyans-ui/cyans-ui#10]
Il tipo di test da fare riguarda la metodologia da utilizzare per ottenere un hot reloading dell'html e del css senza ricaricare la pagina.

**Comment by LucaColonnello** [comment]
Test effettuati fino ad ora:

- sostituzione di una classe registrata come custom element on the fly preservandone lo stato http://jsbin.com/lakiyekaye/1/edit?js,console,output
  - in questo test viene creato un componente semplice che incrementa un contatore ogni volta che viene chiamato il metodo render. Dopo pochi secondi viene richiamato il render per stampare il nuovo numero. Dopo altri secondi viene sostituito il prototipo con uno nuovo che ha un render diverso e richiamato il render.
  - Risultato: il render chiamato al la seconda volta stampa il contenuto del nuovo prototipo sostituito all'originale (simil hot reloading), ma il counter viene incrementato partendo da quello che era precedentemente (lo stato è quindi preservato).

- hot reloading (ispirato a `react-hot-loader`) usando Webpack HMR

  - se ho un questo albero di dipendenze:
     - A.js
       - B.js
         - F.js
       - C.js
     - utilizzando il listener per hot reloading `module.hot.accept('./A' onUpdate)` in un file che import `A.js` (un ipotetica `index.js`), ogni qualvolta aggiorno A o una delle sue dipendenze (B, F, C), la funzione `onUpdate` che ho passato viene chiamata.
     - se nel file `index` sposto l'hot reloading su ad esempio `B.js`, qualora lo modifico ottengo un page reload, in quanto la index non dipende direttamente da `B`, ma da `A` che quindi dipende da `B`. Quindi l'hot reloading tiene in considerazione la catena per assicurarsi che eventuali padri che usano una dipendenza siano al corrente del cambiamento e possano reagire.
     - se inserisco un nuovo listener `module.hot.accept('./B' onUpdate)` dentro il file `A`, questo callback verra chiamato solo se `B` o `F` sono cambiati. Verrà anche chiamato il callback nella index. In questo caso non ho un full page reload, in quanto almeno uno dei padri è del file cambiato è stato notificato.

**Comment by LucaColonnello** [comment]
## Possibile soluzione

Ipotizzando di avere una `index` del playground simile a questa:

```js
// ./playground/index.js
import PlaygroundApp from './app';
import stories from './stories';

const playgroundApp = PlaygroundApp(stories);
```

```js
// ./playground/stories.js
import buttonStories from '../packages/button/stories';

export default [
    buttonStories
];
```

Si potrebbe aggiungere un hot reload del genere (alla fine del file):

```js
if (module.hot) {
  module.hot.accept('./stories', () => {
    // questa funzione dovrebbe richiamare una funzione di update di ogni componente istanziato
    playgroundApp.updateRender();
  });
}
```

La funzione di update potrebbe banalmente recuperare tutti i componenti a schermo e chiamare il render.

```js
function updateRender() {
  const cyElementsOnScreen = Array.map.call(
    document.querySelectorAll('html /deep/ *'),
    el => el.nodeName.toLowerCase()
  )
    .filter((tagName) => tagName.indexOf('cy-') !== -1)
    .map(document.querySelectorAll);

  cyElementsOnScreen.forEach((cyComponents) => {
    Array.forEach.call(cyComponents, component => component.render());
  });
}
```

## Tassello mancante

Quello che manca è come sostituire il prototipo dei componenti cambiati secondo il test di cui sopra (Webpack HMR sostituisce automaticamente i moduli con i precedenti, che vengono persi prima che la funzione di update venga chiamata).

Ci vorrebbe quindi qualcosa che colleziona tutte le classi dei componenti per poter sostituire il prototipo successivamente.

Potrebbe essere un codice che al fondo di ogni componente registra e effettua la sostituzione se necessario. Quindi qualcosa del genere:

```
// questo al fondo di ogni componente (ad esempio al fondo di MyComponent.js)

CYANS_HOT_RELOADER.updateComponentPrototype(MyComponent, __FILENAME__);
```

Questo codice verrebbe cosi eseguito ad ogni salvataggio di questo file o di una sua dipendenza (come ad esempio un file css importato nel componente ;) ).

Per aggiungere tale codice si potrebbe creare un plugin babel che usando AST inserisce queste righe prima del 

## Recap

Quindi il codice che fa update del prototipo servirebbe a sostituire i metodi del componente vecchio con quello nuovo che è assegnato al CustomElement, mentre l'hot reloader verrebbe chiamato dopo, e avrebbe solo il compito di chiamare la funzione di render su ogni componente che c'é a schermo.

**Comment by LucaColonnello** [comment]
@OctoD @equinusocio qua è lunga la cosa, ma vale la pena dare un occhiata!

**Comment by OctoD** [comment]
Appena riesco lo testo, però per me è ok

**Comment by equinusocio** [comment]
Io non ci ho capito na mazza. Per me è la gibolla.

**Comment by LucaColonnello** [comment]
@equinusocio ahahah semplicemente fammi la UI in css per favore, cosi vado avanti con i ticket reali. Puoi anche aspettare un po perche devo fare prima il ticket sul Virtual DOM, ma a breve mi servira!

**Comment by OctoD** [comment]
Butto lì una proposta, molto a caldo. 

Creare un oggetto che:

* Espone un metodo di subscribing verso l'hot reloader  
  * Accetta una stringa per il path. Se tutti i componenti/stories implementano la stessa interfaccia (presentano un metodo `render` o `updateRender`, in automatico all'invocazione del reload, questo metodo verrà eseguito)

Si potrebbe a questo punto in ogni componente/story eseguire il subscribing. 
Da webpack potremmo agilmente rimuovere gli `if` statements tramite extract (avevo provato tempo fa questo plugin e sembrava funzionare abbastanza bene https://github.com/jballant/webpack-strip-block)

Esempio di oggetto che potrebbe funzionare da replacer/listener

```js
class CyansUIHotLoader {
  constructor(scope) {
    if (!scope.cyansuihotload) {
      this.subscriptions = {};
      scope.cyansuihotload = this;
    } else {
      return scope.cyansuihotload;
    }
  }

  /**
   * Invocato all'hot reload, scorre la lista di componenti/storie registrate ed esegue il callback
   * @param path 
   */
  onUpdate(path) {
    if (this.subscriptions[path] && Object.prototype.toString.call(this.subscriptions[path]) === '[object Array]') {
      this.subscriptions[path].forEach(component => {
        const _module = require(path);

        if (_module !== undefined && _module.prototype !== undefined && typeof _module.prototype === 'object') {
          this.replacePrototype(component, _module.prototype);
          component['nome metodo per forzare il render']();
        }
      });
    }
  }

  /**
   * Rimpiazza il prototipo
   * @param path 
   */
  replacePrototype(component, prototype) {
    Object.keys(prototype).forEach(propname => {
      // ¿mumble?
      component.prototype[propname] = prototype[propname];
    });
  }

  /**
   * Sottoscrive un componente/story ad un file. 
   * @param {any} path 
   * @param {any} component 
   * @memberof CyansUIHotLoader
   */
  subscribeComponent(path, component) {
    if (!this.subscriptions[path]) {
      this.subscriptions[path] = [];
    }
    this.subscriptions[path].push(component);
    module.hot.accept(path, () => this.onUpdate(path));
  }
}
```

In fondo ai componenti/stories/whatsoever

```js

/* develblock:start */
new CyansUIHotLoader(window).subscribeComponent('./a.js', VarComponente);
/* develblock:end */

```

**Comment by equinusocio** [comment]
كل واضحة جدا

**Comment by LucaColonnello** [comment]
@octod si una cosa del genere. Solo che deve essere trasparente nei componenti, quindi dobbiamo creare un plugin Babel che aggiunge del codice ai componenti per fare il subscribe! Uno dei pezzi importanti deve essere che non cambia i componenti che non sono stati ricaricati, quindi! Ci arriviamo pian piano, ma se fai un occhiata a come funge grosso modo react-hot-loader penso si capisca meglio di come l'ho spiegato io! ;)

**Comment by LucaColonnello** [comment]
Un altro problema è che il module.hot non puoi farlo così, perché come spiegavo sopra segue tutto l'albero, quindi lancia un errore quando uno dei nostri non fa accept.

**Comment by OctoD** [comment]
Ignoranza mia :-) vado a studiare il sorgente che è meglio.

**Comment by LucaColonnello** [comment]
No ma piu o meno e quello, solo che serve un sistema che in poche parole fa uno stack di componenti da aggiornare, che viene popolato al reload e quando fa update lo consuma. In questo modo viene anche pulito ed e libero per il prossimo reload. Ma per farlo hai bisogno di aggiungere righe di codice al fondo di ogni componente, o come dici tu nella storia che lo importa anche, va bene. E puo essere come hai fatto tu, ma credo che l'hot reloading debba stare fuori, nella root del playground!
