### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by LucaColonnello** [cyans-ui/cyans-ui#6]
Circle CI setup for tests and build

## PR

https://github.com/cyans-ui/cyans-ui/issues/7

**Comment by equinusocio** [comment]
La questione di codacy la escludiamo allora?
https://www.codacy.com/

**Comment by LucaColonnello** [comment]
Per ora per codacy dire di skippare e vedere se abbiamo problemi tipo linting che blocca ecc... Se si ci va nulla penso ad integrarlo! Preferisco iterare che fare tutto a priori!
