### ISSUE TITLE
Spike: Ways of work in dev

### ISSUE THREAD

**Issue by LucaColonnello** [cyans-ui/cyans-ui#8]
L'obiettivo è trovare un playground dove provare i componenti mentre li si fanno!

**Comment by LucaColonnello** [comment]
@OctoD @equinusocio vedendo come si comporta storybook l'effort mi pare troppo.
Trovo piu facile montare alla veloce un pannello con express e un po di html e css e mettere un elenco di componenti che al click lo monta.

Ad esempio si potrebbe avere un file del tipo

```
// ./playground/index.js
import render from './app';

import '../packages/cy-button';

render([
  {
    title: 'Buttons',
    states: [
      {
        name: 'Normal',
        component: () => (<cy-button>Click me</cy-button>)
      },
      {
        name: 'Disabled',
        component: () => (<cy-button disabled>Can't touch me</cy-button>)
      },
    ],
  },
]);
```

Questo dovrebbe quindi generare una piccola app con tutti i componenti in una lista, gruppati e se ci clicchi ti apre la preview, quindi esegue il componente. Piu avanti ci si puo mettere anche la possibilita di modificare il codice...

**Comment by OctoD** [comment]
Per me è ok. L'ideale sarebbe inserire per ogni package il proprio "esempio", andandolo poi a caricare programmaticamente senza dover fare tutto hardcoded.

Tipo se mantenessimo una struttura del fs simile

* ~/cyan-ui
  * packages
    * Package1
      * __story__
        *   index.story.js
      * __test__
      * index.js
      * index.postcss
      * package.json
    * Package2
      * __story__
        *   index.story.js
      * __test__
      * index.js
      * index.postcss
      * package.json
    * Package3
      * __story__
        *   index.story.js
      * __test__
      * index.js
      * index.postcss
      * package.json
    * Package4
      * __story__
        *   index.story.js
      * __test__
      * index.js
      * index.postcss
      * package.json
  * [...] 

E scrivessimo un server così

```js
import * as express from 'express'
import * as path from 'path'
import * as fsutils from '../dirto/fsutils'

let stories = fsutils.readdirRecursive(process.cwd()).filter(name => name.indexOf('__story__') && fsutils.hasExtension('js'));
let routes = stories.map(story => path.basename(story, path.extname(story))).map(story => `/components/${story}`);

routes.forEach((route, index) => {
  express.get(route, (req, res) => {
    res.sendFile(stories[index]);
  });
});

// moar
// ...
// endmoar

app.listen(3000)
```
Ad ogni route sotto `/components` corrisponderebbe un file caricabile dalla index.html (route principale `/`) e dallo script che esegue il componente.

Spero di non aver frainteso :)

**Comment by LucaColonnello** [comment]
Piu o meno potrebbe andare, solo che deve essere tutto in un app unica per rendere facile switchare da un componente ad un altro... Non mi piacerebbe avere diverse pagine da dover caricare.

Mentre avere le varie "storie" per ogni componente e fattibilissimo, ma credo valga comunque la pena caricarle da una index in modo pragmatico invece che facendo un lookup del file system, perche rende forse piu semplice l'hot reloading...
Ma su questo c'e da investigare!

Unica cosa, cosi facendo pero non puoi fare storie che combinano piu componenti se serve, quindi la struttura potrebbe essere un vincolo.

Che dite?

**Comment by equinusocio** [comment]
Quasi sicuramente ci saranno componenti ”composti". Quindi questo ultimo punto potrebbe essere un problema se ho capito bene. Per il resto non ci ho capito quasi nulla, ma mi fido (a parte index.postcss) che non si puo vedere :P

**Comment by LucaColonnello** [comment]
ahahaha ok @equinusocio . Per index postcss non so, e piu una convention quando lavori con node di avere file index per i vari formati. Ma se preferisci style, non fara male!

**Comment by equinusocio** [comment]
`style.postcss`si, please

**Comment by LucaColonnello** [comment]
@OctoD non saprei cosa scegliere. Le storie sicuramente vanno importate a mano nell'app di playground perche dovrebbe essere un app unica, quindi una sola route.

Per le storie nei singoli componenti sono combattuto. Da una parte @equinusocio dice giustamente che ci possono essere componenti composti. Dall'altra, avere componenti composti non significa avere storie disaccoppiate dai componenti...

**Comment by OctoD** [comment]
A questo punto direi che per partire si può optare per una soluzione fatta a mano, non penso che si dovranno creare un centinaio di stories. Iniziamo a delineare più nel concreto una struttura?

**Comment by LucaColonnello** [comment]
Ok! Per me avere le storie nella cartella dei componenti va bene. Ma e comunque indispensabile fare un import statico, quindi sarebbe da fare che la index del playground si importa la index delle storie di ogni componente... Altrimenti ci potrebbero essere problemi se in futuro si vuole fare l'hot reloading (che sta diventando difficile a quanto vedo)...

**Comment by LucaColonnello** [comment]
Direi che possiamo chiudere qui e cominciare a dividere task per farlo! Credo faro delle spike per l'hot reloading!
